### ISSUE TITLE
Proposal: change CMD

### ISSUE THREAD

**Issue by colthreepv** [restorecommerce/pdf-rendering-srv#1]
Hi, using `npm start` in the CMD is executing `nodemon` in the container (that's based on the [state of package.json](https://github.com/alvarcarto/url-to-pdf-api/blob/970207bfcd372ebeb9f9373295342963ea0af6e3/package.json#L10) of main project)

I would rather not use `nodemon` in production, as it is really not necessary, as the source code is not ever changing

I would suggest to replace with
```
CMD ["node", "."]
```
This would run the `main` file specified in `package.json`

**Comment by vanthome** [comment]
hmm, but nodemon also covers the reload if the server crashes... Yes this should can be done also by Kubernetes or whatever is running the workload but given the low overhead why not keep it?

**Comment by colthreepv** [comment]
just quitting if there is a crash is the standard behaviour of any dockerized application  
If the user desires to auto-restart the container, it can use `docker run --restart always` or kubernetes policy or anything really
