### ISSUE TITLE
Docker image does not include the latest `url-to-pdf-api` code

### ISSUE THREAD

**Issue by tomasc** [restorecommerce/pdf-rendering-srv#2]
Would it be possible to rebuild the image? Recently there was an update supporting `screenshot.selector` merged (https://github.com/alvarcarto/url-to-pdf-api/pull/128) which I would like to use.

Perhaps it would make sense to set up automated builds?

Thank you!

**Comment by vanthome** [comment]
done

**Comment by tomasc** [comment]
@vanthome thanks a lot for such a prompt update!
