### ISSUE TITLE
Alpine based image support?

### ISSUE THREAD

**Issue by ddliu** [restorecommerce/pdf-rendering-srv#3]
The image size seems too big(500Mb), it'll be great if we can have Alpine as a base image.

**Comment by vanthome** [comment]
I think we tired with Alpine already but some stuff was missing. Feel free to create a PR if you know how it's possible.

**Comment by predkambrij** [comment]
Parent image is not updating anymore. It probably makes more sense to just install latest version of browser, available in the OS (parent image is using ubuntu 18.04 which would be also good to replace with 22.04)

**Comment by vanthome** [comment]
there is a major rewrite of this service in Rust underway. With that, this issue will be irrelevant. Please stay tuned.
