### ISSUE TITLE
Health check endpoint

### ISSUE THREAD

**Issue by barrypitman** [restorecommerce/pdf-rendering-srv#5]
Hi, 

Thanks for this sharing this repo/docker image. In the "latest" image currently deployed on docker hub, there is no "healthcheck" endpoint that we can use, everything that I've tried returns 404. 

I see that https://github.com/alvarcarto/url-to-pdf-api has since added a /healthcheck endpoint, so AFAIK it would just be a matter of building and pushing a new version of this image to Dockerhub. 

I could create a duplicate image on dockerhub, but if you could deploy an update to your existing image, I think that would be best. 

Thanks in advance

**Comment by vanthome** [comment]
there is a major rewrite of this service in Rust underway. With that, this issue will be irrelevant. Please stay tuned.
